---
- name: Install pip
  hosts: localhost
  become: true
  tasks:
    - package:
        name: pip
        state: present

- name: Setup Ansible for talking with Linode
  hosts: localhost
  tasks:
    - pip:
        name: linode_api4

- name: Setup SMTP relay
  hosts: smtp-relay
  gather_facts: false
  roles:
    - linode_host
    - dnf_automatic_updated
    - postfix
